# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: v1
kind: Service
metadata:
  namespace: guestbook
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # Note: If you plan to use k8s ingress to terminate incoming requests, 
  # then change the frontend service type to: Cluster-IP
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
    protocol: TCP
    targetPort: 80  
  selector:
    app: guestbook
    tier: frontend
