---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-leader-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi
  resources:
    requests:
      storage: 2Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-follower-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: synology-nfs 
  resources:
    requests:
      storage: 5Gi
