---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-leader-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default-storageclass
  resources:
    requests:
      storage: 2Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-follower-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: files-storageclass 
  resources:
    requests:
      storage: 5Gi
